name: for 919

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: N1/.config
  DIY_SH: N1/diy.sh
  #FILES: N1/files
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Free up space - Initial
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: flase
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq install -y \
          ack antlr3 asciidoc autoconf automake autopoint binutils bison \
          build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler \
          ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev \
          gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
          libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool \
          libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build \
          p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply \
          python3-docutils python3-pyelftools qemu-utils re2c rsync scons \
          squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim \
          wget xmlto xxd zlib1g-dev zstd \
          libfuse-dev fuse  # 新增关键依赖
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E apt-get -qq autoclean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        ccache -M 10G # Limit ccache size
        df -hT

    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH --single-branch --depth=1 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        df -hT

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install libfuse  # 确保 FUSE 包被安装
        df -hT

    - name: Load custom config
      run: |
        [ -e $FILES ] && mv $FILES openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_SH
        df -hT

    - name: Configure FUSE and dependencies
      working-directory: ./openwrt
      run: |
        echo "CONFIG_FUSE_FS=y" >> .config
        echo "CONFIG_PACKAGE_kmod-fuse=y" >> .config
        echo "CONFIG_PACKAGE_libfuse=y" >> .config
        echo "CONFIG_PACKAGE_alist=y" >> .config
        make defconfig
        df -hT

    - name: SSH connect to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true') || contains(github.event.action, 'ssh')

    - name: Download package
      working-directory: ./openwrt
      run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
          df -hT

    - name: Compile the firmware
      run: |
        chmod -R 755 openwrt
        cd openwrt
        echo -e "$(nproc) thread compile"
        export CGO_ENABLED=0
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "compile_status=success" >> $GITHUB_ENV
        df -hT

    - name: Safe cleanup after compilation
      run: |
        # 安全删除目标文件（只删除文件，不删除目录）
        rm -rf /home/runner/work/test/test/openwrt/bin/targets/*/*/packages || true
        rm -rf /home/runner/work/test/test/openwrt/bin/targets/*/*/buildinfo || true
        rm -rf /home/runner/work/test/test/openwrt/bin/targets/*/*/profiles || true
        rm -rf /home/runner/work/test/test/openwrt/bin/targets/*/*/sha256sums || true
        
        # 安全删除 .o 文件（只删除文件）
        find /workdir/openwrt -name "*.o" -type f -exec rm -f {} \; 2>/dev/null || true
        
        # 安全删除 .log 文件
        find /workdir/openwrt -name "*.log" -type f -exec rm -f {} \; 2>/dev/null || true
        
        # 清理 ccache 缓存
        ccache -c || true
        
        df -hT

    - name: Free up space - Compile Post
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: 清理磁盘空间
      run: |
        mkdir -p /workdir/upload
        # 复制固件文件
        cp openwrt/bin/targets/*/*/*.tar.gz /workdir/upload/ 2>/dev/null || true
        cp openwrt/bin/targets/*/*/*.img.gz /workdir/upload/ 2>/dev/null || true
        
        # 显示磁盘使用情况
        sudo du -h --max-depth=1 /workdir | sort -nr | head -10
        df -hT

    - name: Package armsr as openwrt
      if: ${{ env.compile_status }} == 'success' && !cancelled()
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        KERNEL_VERSION_NAME: 6.12.y_6.6.y
        KERNEL_AUTO_LATEST: true
        PACKAGE_SOC: s905d
        GZIP_IMGS: .xz
        KERNEL_REPO_URL: breakingbadboy/OpenWrt
        SCRIPT_DIY_PATH: N1/mk_s905d_n1.sh
        WHOAMI: test
        SW_FLOWOFFLOAD: 0
        SFE_FLOW: 0

    - name: 整理文件
      run: |
         mkdir -p /workdir/upload
          # 复制打包后的文件
         cp -f /opt/openwrt_packit/output/* /workdir/upload/ 2>/dev/null || echo "No packit output files found"
    
          # 显示上传目录内容
         echo "Files in upload directory:"
          ls -la /workdir/upload/ || true
    
          df -hT

    - name: Generate timestamp for release tag
      run: |
        echo "RELEASE_TAG=OpenWrt_$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

    - name: Upload firmware to release
      if: ${{ env.compile_status }} == 'success' && !cancelled()
      uses: softprops/action-gh-release@v1
      with:
        files: /workdir/upload/*
        tag_name: ${{ env.RELEASE_TAG }}
        name: OpenWrt Build ${{ env.RELEASE_TAG }}
        body: |
            首次使用建议全新刷写
            * 基本信息
            IP: 192.168.110.241
            账户: root
            密码: password
      env:
          GITHUB_TOKEN: ${{ secrets.GI_TOKEN }}
    - name: Delete old releases (keep only latest 1)
      uses: actions/github-script@v6
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
           owner: context.repo.owner,
           repo: context.repo.repo,
           per_page: 100
          });
      
           const sortedReleases = releases.data.sort((a, b) => 
             new Date(b.created_at) - new Date(a.created_at)
           );
      
           for (let i = 2; i < sortedReleases.length; i++) {
            const release = sortedReleases[i];
            console.log(`Deleting old release: ${release.tag_name}`);
        
             await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id
            });
        
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${release.tag_name}`
              });
              } catch (error) {
              console.log(`Tag ${release.tag_name} already deleted or not found`);
            }
          }
      
          return `Kept 1 release, deleted ${sortedReleases.length - 1} old releases`;

    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2.0.6
      with:
        token: ${{ secrets.GI_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0

 
